# Generated by Django 6.0.8 on 2026-08-06 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Пусто = официальный набор (добавлен через /admin/). Заполнено = личный набор пользователя.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
