# Generated by Django 6.0.8 on 2026-08-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='explanation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('verb_tense', 'Verb tense'), ('articles', 'Articles (a/an/the)'), ('prepositions', 'Prepositions'), ('subject_verb', 'Subject-verb agreement'), ('word_order', 'Word order'), ('vocabulary', 'Vocabulary / word choice'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
