# Generated by Django 6.0.8 on 2026-08-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=300)),
                ('wrong_answer_1', models.CharField(max_length=300)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=300)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingtext')),
            ],
        ),
    ]
